DROP TABLE cnm_c_field CASCADE;
DROP TABLE cnm_c_field_type CASCADE;
DROP TABLE cnm_c_immagine CASCADE;
DROP TABLE cnm_c_immagine_report CASCADE;
DROP TABLE cnm_c_parametro CASCADE;
DROP TABLE cnm_c_report CASCADE;
DROP TABLE cnm_c_schedulatore CASCADE;
DROP TABLE cnm_d_ambito CASCADE;
DROP TABLE cnm_d_articolo CASCADE;
DROP TABLE cnm_d_categoria_allegato CASCADE;
DROP TABLE cnm_d_comma CASCADE;
DROP TABLE cnm_d_comune CASCADE;
DROP TABLE cnm_d_elemento_elenco CASCADE;
DROP TABLE cnm_d_elenco CASCADE;
DROP TABLE cnm_d_ente CASCADE;
DROP TABLE cnm_d_gruppo CASCADE;
DROP TABLE cnm_d_lettera CASCADE;
DROP TABLE cnm_d_messaggio CASCADE;
DROP TABLE cnm_d_modalita_notifica CASCADE;
DROP TABLE cnm_d_nazione CASCADE;
DROP TABLE cnm_d_norma CASCADE;
DROP TABLE cnm_d_origine CASCADE;
DROP TABLE cnm_d_provincia CASCADE;
DROP TABLE cnm_d_regione CASCADE;
DROP TABLE cnm_d_ruolo CASCADE;
DROP TABLE cnm_d_ruolo_soggetto CASCADE;
DROP TABLE cnm_d_stato_allegato CASCADE;
DROP TABLE cnm_d_stato_file CASCADE;
DROP TABLE cnm_d_stato_ord_verb_sog CASCADE;
DROP TABLE cnm_d_stato_ordinanza CASCADE;
DROP TABLE cnm_d_stato_piano_rate CASCADE;
DROP TABLE cnm_d_stato_rata CASCADE;
DROP TABLE cnm_d_stato_record CASCADE;
DROP TABLE cnm_d_stato_riscossione CASCADE;
DROP TABLE cnm_d_stato_sollecito CASCADE;
DROP TABLE cnm_d_stato_verbale CASCADE;
DROP TABLE cnm_d_tipo_allegato CASCADE;
DROP TABLE cnm_d_tipo_file CASCADE;
DROP TABLE cnm_d_tipo_messaggio CASCADE;
DROP TABLE cnm_d_tipo_ordinanza CASCADE;
DROP TABLE cnm_d_tipo_record CASCADE;
DROP TABLE cnm_d_tipo_tributo CASCADE;
DROP TABLE cnm_d_use_case CASCADE;
DROP TABLE cnm_d_utilizzo CASCADE;
DROP TABLE cnm_d_utilizzo_allegato CASCADE;
DROP TABLE cnm_r_allegato_ord_verb_sog CASCADE;
DROP TABLE cnm_r_allegato_ordinanza CASCADE;
DROP TABLE cnm_r_allegato_piano_rate CASCADE;
DROP TABLE cnm_r_allegato_sollecito CASCADE;
DROP TABLE cnm_r_allegato_verb_sog CASCADE;
DROP TABLE cnm_r_allegato_verbale CASCADE;
DROP TABLE cnm_r_ente_norma CASCADE;
DROP TABLE cnm_r_funzionario_istruttore CASCADE;
DROP TABLE cnm_r_notifica_ordinanza CASCADE;
DROP TABLE cnm_r_notifica_piano_rate CASCADE;
DROP TABLE cnm_r_notifica_sollecito CASCADE;
DROP TABLE cnm_r_ordinanza_verb_sog CASCADE;
DROP TABLE cnm_r_sogg_rata CASCADE;
DROP TABLE cnm_r_tipo_allegato_so CASCADE;
DROP TABLE cnm_r_tipo_allegato_sv CASCADE;
DROP TABLE cnm_r_use_case_ruolo CASCADE;
DROP TABLE cnm_r_user_ente CASCADE;
DROP TABLE cnm_r_verbale_illecito CASCADE;
DROP TABLE cnm_r_verbale_soggetto CASCADE;
DROP TABLE cnm_s_comune CASCADE;
DROP TABLE cnm_s_nazione CASCADE;
DROP TABLE cnm_s_provincia CASCADE;
DROP TABLE cnm_s_regione CASCADE;
DROP TABLE cnm_s_stato_ordinanza CASCADE;
DROP TABLE cnm_s_stato_verbale CASCADE;
DROP TABLE cnm_t_allegato CASCADE;
DROP TABLE cnm_t_allegato_field CASCADE;
DROP TABLE cnm_t_calendario CASCADE;
DROP TABLE cnm_t_file CASCADE;
DROP TABLE cnm_t_file_ritorno CASCADE;
DROP TABLE cnm_t_notifica CASCADE;
DROP TABLE cnm_t_ordinanza CASCADE;
DROP TABLE cnm_t_persona CASCADE;
DROP TABLE cnm_t_piano_rate CASCADE;
DROP TABLE cnm_t_rata CASCADE;
DROP TABLE cnm_t_record CASCADE;
DROP TABLE cnm_t_record_n2 CASCADE;
DROP TABLE cnm_t_record_n3 CASCADE;
DROP TABLE cnm_t_record_n4 CASCADE;
DROP TABLE cnm_t_residenza CASCADE;
DROP TABLE cnm_t_record_ritorno CASCADE;
DROP TABLE cnm_t_riscossione CASCADE;
DROP TABLE cnm_t_societa CASCADE;
DROP TABLE cnm_t_soggetto CASCADE;
DROP TABLE cnm_t_sollecito CASCADE;
DROP TABLE cnm_t_user CASCADE;
DROP TABLE cnm_t_verbale CASCADE;
DROP TABLE cnm_tmp_file CASCADE;
DROP TABLE dt_assoc_esteri_ministero CASCADE;
DROP TABLE dt_assoc_esteri_ministero_div CASCADE;
DROP TABLE dt_limiti_amministrativi CASCADE;
DROP TABLE dt_limiti_amministrativi_div CASCADE;
DROP TABLE dt_stati_esteri_istat CASCADE;
DROP TABLE dt_stati_esteri_istat_div CASCADE;
DROP TABLE dt_stati_esteri_ministero CASCADE;
DROP TABLE dt_stati_esteri_ministero_div CASCADE;

DROP FUNCTION aggiornacomune(pidcomune numeric,pidcomuneprev numeric,pidcomunenext numeric,pcodistatcomune character varying,pcodbelfiorecomune character varying,pdenomcomune character varying,pidprovincia numeric,piniziovalidita date,pfinevalidita date);
DROP FUNCTION aggiornacomuni();
DROP FUNCTION aggiornanazione(pIdStato IN NUMERIC, pIdStatoPrev IN NUMERIC, pIdStatoNext IN NUMERIC, pCodIstatNazione IN CHARACTER VARYING, pCodBelfioreNazione IN CHARACTER VARYING, pDenomNazione IN CHARACTER VARYING, pInizioValidita IN DATE, pFineValidita IN DATE);
DROP FUNCTION aggiornanazioni();
DROP FUNCTION aggiornaprovince();
DROP FUNCTION aggiornaprovincia(pcodprovincia character varying,pdenomprovincia character varying,psiglaprovincia character varying,pidregione numeric,piniziovalidita date,pfinevalidita date);
DROP FUNCTION aggiornaregione(pcodregione character varying,pdenomregione character varying,pidnazione numeric,piniziovalidita date,pfinevalidita date);
DROP FUNCTION aggiornaregioni();
DROP FUNCTION getidnazione(pcodistatnazione character varying);
DROP FUNCTION getidprovincia(pcodprovincia character varying);
DROP FUNCTION getidregione(pcodregione character varying);
DROP FUNCTION getnextidcomune();
DROP FUNCTION getnextidnazione();
DROP FUNCTION getnextidprovincia();
DROP FUNCTION getnextidregione();
DROP FUNCTION getnextidscomune();
DROP FUNCTION getnextidsnazione();
DROP FUNCTION getnextidsprovincia();
DROP FUNCTION getnextidsregione();
DROP FUNCTION preparafiledascaricare();
DROP FUNCTION puliscidenominazione(pdenomcomune character varying);
