/*
 * Swagger TSDDR - Swagger 2.0
 * TSDDR API description
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.conam.conambl.integration.epay.rest.model;

import java.util.Objects;

import org.codehaus.jackson.annotate.JsonProperty;


/**
 * DebtPositionReference
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-04-03T15:13:52.122Z")
public class DebtPositionReference {
  @JsonProperty("codiceAvviso")
  private String codiceAvviso = null;

  @JsonProperty("codiceEsito")
  private String codiceEsito = null;

  @JsonProperty("descrizioneEsito")
  private String descrizioneEsito = null;

  @JsonProperty("identificativoPagamento")
  private String identificativoPagamento = null;

  @JsonProperty("iuv")
  private String iuv = null;

  public DebtPositionReference codiceAvviso(String codiceAvviso) {
    this.codiceAvviso = codiceAvviso;
    return this;
  }

   /**
   * Get codiceAvviso
   * @return codiceAvviso
  **/
  
  public String getCodiceAvviso() {
    return codiceAvviso;
  }

  public void setCodiceAvviso(String codiceAvviso) {
    this.codiceAvviso = codiceAvviso;
  }

  public DebtPositionReference codiceEsito(String codiceEsito) {
    this.codiceEsito = codiceEsito;
    return this;
  }

   /**
   * Get codiceEsito
   * @return codiceEsito
  **/
  
  public String getCodiceEsito() {
    return codiceEsito;
  }

  public void setCodiceEsito(String codiceEsito) {
    this.codiceEsito = codiceEsito;
  }

  public DebtPositionReference descrizioneEsito(String descrizioneEsito) {
    this.descrizioneEsito = descrizioneEsito;
    return this;
  }

   /**
   * Get descrizioneEsito
   * @return descrizioneEsito
  **/
  
  public String getDescrizioneEsito() {
    return descrizioneEsito;
  }

  public void setDescrizioneEsito(String descrizioneEsito) {
    this.descrizioneEsito = descrizioneEsito;
  }

  public DebtPositionReference identificativoPagamento(String identificativoPagamento) {
    this.identificativoPagamento = identificativoPagamento;
    return this;
  }

   /**
   * Get identificativoPagamento
   * @return identificativoPagamento
  **/
  
  public String getIdentificativoPagamento() {
    return identificativoPagamento;
  }

  public void setIdentificativoPagamento(String identificativoPagamento) {
    this.identificativoPagamento = identificativoPagamento;
  }

  public DebtPositionReference iuv(String iuv) {
    this.iuv = iuv;
    return this;
  }

   /**
   * Get iuv
   * @return iuv
  **/
  
  public String getIuv() {
    return iuv;
  }

  public void setIuv(String iuv) {
    this.iuv = iuv;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DebtPositionReference debtPositionReference = (DebtPositionReference) o;
    return Objects.equals(this.codiceAvviso, debtPositionReference.codiceAvviso) &&
        Objects.equals(this.codiceEsito, debtPositionReference.codiceEsito) &&
        Objects.equals(this.descrizioneEsito, debtPositionReference.descrizioneEsito) &&
        Objects.equals(this.identificativoPagamento, debtPositionReference.identificativoPagamento) &&
        Objects.equals(this.iuv, debtPositionReference.iuv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiceAvviso, codiceEsito, descrizioneEsito, identificativoPagamento, iuv);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DebtPositionReference {\n");
    
    sb.append("    codiceAvviso: ").append(toIndentedString(codiceAvviso)).append("\n");
    sb.append("    codiceEsito: ").append(toIndentedString(codiceEsito)).append("\n");
    sb.append("    descrizioneEsito: ").append(toIndentedString(descrizioneEsito)).append("\n");
    sb.append("    identificativoPagamento: ").append(toIndentedString(identificativoPagamento)).append("\n");
    sb.append("    iuv: ").append(toIndentedString(iuv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

