/*
 * Swagger TSDDR - Swagger 2.0
 * TSDDR API description
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.conam.conambl.integration.epay.rest.model;

import java.math.BigDecimal;
import java.util.Objects;

import org.codehaus.jackson.annotate.JsonProperty;

/**
 * PaymentComponent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-04-03T15:13:52.122Z")
public class PaymentComponent {
  @JsonProperty("annoAccertamento")
  private Integer annoAccertamento = null;

  @JsonProperty("causale")
  private String causale = null;

  @JsonProperty("datiSpecificiRiscossione")
  private String datiSpecificiRiscossione = null;

  @JsonProperty("importo")
  private BigDecimal importo = null;

  @JsonProperty("numeroAccertamento")
  private String numeroAccertamento = null;

  @JsonProperty("progressivo")
  private Integer progressivo = null;

  public PaymentComponent annoAccertamento(Integer annoAccertamento) {
    this.annoAccertamento = annoAccertamento;
    return this;
  }

   /**
   * Get annoAccertamento
   * @return annoAccertamento
  **/
  
  public Integer getAnnoAccertamento() {
    return annoAccertamento;
  }

  public void setAnnoAccertamento(Integer annoAccertamento) {
    this.annoAccertamento = annoAccertamento;
  }

  public PaymentComponent causale(String causale) {
    this.causale = causale;
    return this;
  }

   /**
   * Get causale
   * @return causale
  **/
  
  public String getCausale() {
    return causale;
  }

  public void setCausale(String causale) {
    this.causale = causale;
  }

  public PaymentComponent datiSpecificiRiscossione(String datiSpecificiRiscossione) {
    this.datiSpecificiRiscossione = datiSpecificiRiscossione;
    return this;
  }

   /**
   * Get datiSpecificiRiscossione
   * @return datiSpecificiRiscossione
  **/
  
  public String getDatiSpecificiRiscossione() {
    return datiSpecificiRiscossione;
  }

  public void setDatiSpecificiRiscossione(String datiSpecificiRiscossione) {
    this.datiSpecificiRiscossione = datiSpecificiRiscossione;
  }

  public PaymentComponent importo(BigDecimal importo) {
    this.importo = importo;
    return this;
  }

   /**
   * Get importo
   * @return importo
  **/
  
  public BigDecimal getImporto() {
    return importo;
  }

  public void setImporto(BigDecimal importo) {
    this.importo = importo;
  }

  public PaymentComponent numeroAccertamento(String numeroAccertamento) {
    this.numeroAccertamento = numeroAccertamento;
    return this;
  }

   /**
   * Get numeroAccertamento
   * @return numeroAccertamento
  **/
  
  public String getNumeroAccertamento() {
    return numeroAccertamento;
  }

  public void setNumeroAccertamento(String numeroAccertamento) {
    this.numeroAccertamento = numeroAccertamento;
  }

  public PaymentComponent progressivo(Integer progressivo) {
    this.progressivo = progressivo;
    return this;
  }

   /**
   * Get progressivo
   * @return progressivo
  **/
  
  public Integer getProgressivo() {
    return progressivo;
  }

  public void setProgressivo(Integer progressivo) {
    this.progressivo = progressivo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentComponent paymentComponent = (PaymentComponent) o;
    return Objects.equals(this.annoAccertamento, paymentComponent.annoAccertamento) &&
        Objects.equals(this.causale, paymentComponent.causale) &&
        Objects.equals(this.datiSpecificiRiscossione, paymentComponent.datiSpecificiRiscossione) &&
        Objects.equals(this.importo, paymentComponent.importo) &&
        Objects.equals(this.numeroAccertamento, paymentComponent.numeroAccertamento) &&
        Objects.equals(this.progressivo, paymentComponent.progressivo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(annoAccertamento, causale, datiSpecificiRiscossione, importo, numeroAccertamento, progressivo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentComponent {\n");
    
    sb.append("    annoAccertamento: ").append(toIndentedString(annoAccertamento)).append("\n");
    sb.append("    causale: ").append(toIndentedString(causale)).append("\n");
    sb.append("    datiSpecificiRiscossione: ").append(toIndentedString(datiSpecificiRiscossione)).append("\n");
    sb.append("    importo: ").append(toIndentedString(importo)).append("\n");
    sb.append("    numeroAccertamento: ").append(toIndentedString(numeroAccertamento)).append("\n");
    sb.append("    progressivo: ").append(toIndentedString(progressivo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

