/*
 * Swagger TSDDR - Swagger 2.0
 * TSDDR API description
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.conam.conambl.integration.epay.rest.model;

import java.math.BigDecimal;
import java.util.Objects;

import org.codehaus.jackson.annotate.JsonProperty;

/**
 * PaymentData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-04-03T15:13:52.122Z")
public class PaymentData {
  @JsonProperty("causale")
  private String causale = null;

  @JsonProperty("codiceFiscalePartitaIVAPagatore")
  private String codiceFiscalePartitaIVAPagatore = null;

  @JsonProperty("cognome")
  private String cognome = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("identificativoPagamento")
  private String identificativoPagamento = null;

  @JsonProperty("importo")
  private BigDecimal importo = null;

  @JsonProperty("nome")
  private String nome = null;

  @JsonProperty("notePerIlPagatore")
  private String notePerIlPagatore = null;

  @JsonProperty("ragioneSociale")
  private String ragioneSociale = null;

  public PaymentData causale(String causale) {
    this.causale = causale;
    return this;
  }

   /**
   * Get causale
   * @return causale
  **/
  
  public String getCausale() {
    return causale;
  }

  public void setCausale(String causale) {
    this.causale = causale;
  }

  public PaymentData codiceFiscalePartitaIVAPagatore(String codiceFiscalePartitaIVAPagatore) {
    this.codiceFiscalePartitaIVAPagatore = codiceFiscalePartitaIVAPagatore;
    return this;
  }

   /**
   * Get codiceFiscalePartitaIVAPagatore
   * @return codiceFiscalePartitaIVAPagatore
  **/
  
  public String getCodiceFiscalePartitaIVAPagatore() {
    return codiceFiscalePartitaIVAPagatore;
  }

  public void setCodiceFiscalePartitaIVAPagatore(String codiceFiscalePartitaIVAPagatore) {
    this.codiceFiscalePartitaIVAPagatore = codiceFiscalePartitaIVAPagatore;
  }

  public PaymentData cognome(String cognome) {
    this.cognome = cognome;
    return this;
  }

   /**
   * Get cognome
   * @return cognome
  **/
  
  public String getCognome() {
    return cognome;
  }

  public void setCognome(String cognome) {
    this.cognome = cognome;
  }

  public PaymentData email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public PaymentData identificativoPagamento(String identificativoPagamento) {
    this.identificativoPagamento = identificativoPagamento;
    return this;
  }

   /**
   * Get identificativoPagamento
   * @return identificativoPagamento
  **/
  
  public String getIdentificativoPagamento() {
    return identificativoPagamento;
  }

  public void setIdentificativoPagamento(String identificativoPagamento) {
    this.identificativoPagamento = identificativoPagamento;
  }

  public PaymentData importo(BigDecimal importo) {
    this.importo = importo;
    return this;
  }

   /**
   * Get importo
   * @return importo
  **/
  
  public BigDecimal getImporto() {
    return importo;
  }

  public void setImporto(BigDecimal importo) {
    this.importo = importo;
  }

  public PaymentData nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Get nome
   * @return nome
  **/
  
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public PaymentData notePerIlPagatore(String notePerIlPagatore) {
    this.notePerIlPagatore = notePerIlPagatore;
    return this;
  }

   /**
   * Get notePerIlPagatore
   * @return notePerIlPagatore
  **/
  
  public String getNotePerIlPagatore() {
    return notePerIlPagatore;
  }

  public void setNotePerIlPagatore(String notePerIlPagatore) {
    this.notePerIlPagatore = notePerIlPagatore;
  }

  public PaymentData ragioneSociale(String ragioneSociale) {
    this.ragioneSociale = ragioneSociale;
    return this;
  }

   /**
   * Get ragioneSociale
   * @return ragioneSociale
  **/
  
  public String getRagioneSociale() {
    return ragioneSociale;
  }

  public void setRagioneSociale(String ragioneSociale) {
    this.ragioneSociale = ragioneSociale;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentData paymentData = (PaymentData) o;
    return Objects.equals(this.causale, paymentData.causale) &&
        Objects.equals(this.codiceFiscalePartitaIVAPagatore, paymentData.codiceFiscalePartitaIVAPagatore) &&
        Objects.equals(this.cognome, paymentData.cognome) &&
        Objects.equals(this.email, paymentData.email) &&
        Objects.equals(this.identificativoPagamento, paymentData.identificativoPagamento) &&
        Objects.equals(this.importo, paymentData.importo) &&
        Objects.equals(this.nome, paymentData.nome) &&
        Objects.equals(this.notePerIlPagatore, paymentData.notePerIlPagatore) &&
        Objects.equals(this.ragioneSociale, paymentData.ragioneSociale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(causale, codiceFiscalePartitaIVAPagatore, cognome, email, identificativoPagamento, importo, nome, notePerIlPagatore, ragioneSociale);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentData {\n");
    
    sb.append("    causale: ").append(toIndentedString(causale)).append("\n");
    sb.append("    codiceFiscalePartitaIVAPagatore: ").append(toIndentedString(codiceFiscalePartitaIVAPagatore)).append("\n");
    sb.append("    cognome: ").append(toIndentedString(cognome)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    identificativoPagamento: ").append(toIndentedString(identificativoPagamento)).append("\n");
    sb.append("    importo: ").append(toIndentedString(importo)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    notePerIlPagatore: ").append(toIndentedString(notePerIlPagatore)).append("\n");
    sb.append("    ragioneSociale: ").append(toIndentedString(ragioneSociale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

