/**
 * StadocStadoc.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Nov 13, 2013 (09:13:21 GMT) WSDL2Java emitter.
 */

package it.csi.conam.conambl.integration.beans;

public interface StadocStadoc extends java.rmi.Remote {
    public boolean testResources() throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.CSIException;
    public it.csi.conam.conambl.integration.beans.InvocationNode selfCheck(it.csi.conam.conambl.integration.beans.CalledResource[] in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.CSIException;
    public boolean hasSelfCheck() throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.CSIException;
    public it.csi.conam.conambl.integration.beans.ResponseArchiviaDocumento archiviaDocumentoLogico(it.csi.conam.conambl.integration.beans.RequestArchiviaDocumentoLogico in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.ArchiviaDocumentoException;
    public it.csi.conam.conambl.integration.beans.ResponseArchiviaDocumento archiviaDocumentoFisico(it.csi.conam.conambl.integration.beans.RequestArchiviaDocumentoFisico in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.ArchiviaDocumentoException;
    public it.csi.conam.conambl.integration.beans.ResponseProtocollaDocumento protocollaDocumentoLogico(it.csi.conam.conambl.integration.beans.RequestProtocollaDocumentoLogico in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.ProtocollaDocumentoException;
    public it.csi.conam.conambl.integration.beans.ResponseProtocollaDocumento protocollaDocumentoFisico(it.csi.conam.conambl.integration.beans.RequestProtocollaDocumentoFisico in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.ProtocollaDocumentoException;
    public it.csi.conam.conambl.integration.beans.ResponseSalvaDocumento salvaDocumento(it.csi.conam.conambl.integration.beans.RequestSalvaDocumento in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SalvaDocumentoException, it.csi.conam.conambl.integration.beans.SystemException;
    public it.csi.conam.conambl.integration.beans.ResponseEliminaDocumento eliminaDocumento(it.csi.conam.conambl.integration.beans.RequestEliminaDocumento in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.EliminaDocumentoException;
    public it.csi.conam.conambl.integration.beans.ResponseSalvaDocumentoLogico salvaDocumentoLogico(it.csi.conam.conambl.integration.beans.RequestSalvaDocumentoLogico in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SalvaDocumentoException, it.csi.conam.conambl.integration.beans.SystemException;
    public it.csi.conam.conambl.integration.beans.ResponseCambiaStatoRichiesta cambiaStatoRichiesta(it.csi.conam.conambl.integration.beans.RequestCambiaStatoRichiesta in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.CambiaStatoRichiestaException;
    public it.csi.conam.conambl.integration.beans.ResponseRecuperaRiferimentoDocumentoFisico recuperaRiferimentoDocumentoFisico(it.csi.conam.conambl.integration.beans.RequestRecuperaRiferimentoDocumentoFisico in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.RecuperaRiferimentoDocumentoFisicoException;
    public it.csi.conam.conambl.integration.beans.ResponseRicercaDocumento ricercaDocumento(it.csi.conam.conambl.integration.beans.RequestRicercaDocumento in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.RicercaDocumentoException;
    public it.csi.conam.conambl.integration.beans.ResponseAssociaDocumentoFisico associaDocumentoFisico(it.csi.conam.conambl.integration.beans.RequestAssociaDocumentoFisico in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.AssociaDocumentoFisicoException;
    public it.csi.conam.conambl.integration.beans.ResponseAggiungiAllegato aggiungiAllegato(it.csi.conam.conambl.integration.beans.RequestAggiungiAllegato in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.AggiungiAllegatoException;
    public it.csi.conam.conambl.integration.beans.ResponseRicercaAllegato ricercaAllegato(it.csi.conam.conambl.integration.beans.RequestRicercaAllegato in0) throws java.rmi.RemoteException, it.csi.conam.conambl.integration.beans.UnrecoverableException, it.csi.conam.conambl.integration.beans.CSIException, it.csi.conam.conambl.integration.beans.SystemException, it.csi.conam.conambl.integration.beans.RicercaAllegatoException;
}
